### ISSUE TITLE
Copy message from other channel

### ISSUE THREAD

**Issue by ashkufaraz** [ide2/TelegramHandler#12]
Hi
Sorry,I have a question about your project(telegram).
Can I get the message channels that I'm not their admin?
I want write a script that read message from other chanel and write to
my chanel.
I can do it?
best regards
thanks

**Comment by renan-m-p** [comment]
Hello
Yes you can do it, but not with this project. This project is a handler for telegram using monolog [1].
The telegram API allows you to do it. [2]

Thanks

[1] https://github.com/Seldaek/monolog
[2] https://core.telegram.org/api

**Comment by ashkufaraz** [comment]
very thanks
